[package]
name = "api"
authors.workspace = true
version.workspace =  true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/extension_api.rs"

[dependencies]
wit-bindgen = { workspace = true }